version: '3'

services:
  choc:
    build:
      context: ../../
      dockerfile: config/.docker/Dockerfile
    ports:
      - '3000:3000'
    external_links:
      - chocmongo
    networks:
      - choc
  chocmongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'data:/data/db'
    networks:
      - choc

volumes:
  data:

networks:
  choc:
